version: '3.8'

services:
  backend:
    container_name: backend_agromarket
    build: .
    ports:
      - "5080:5080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    restart: unless-stopped
